version: '3.7'

services:
  iris:
    #image: containers.intersystems.com/intersystems/iris:2024.1
    build:
      context: ./iris
      dockerfile: Dockerfile
    init: true
    container_name: nopwsiris
    ports:
       - "8082:1972"
    environment:
      - TZ=JST-9
    volumes:
      - ./iris:/ISC

  webgw:
    image: containers.intersystems.com/intersystems/webgateway:2024.1
    container_name: webgw1
    init: true
    ports:
      - 8080:80
      - 8443:443
    environment:
    - ISC_CSP_CONF_FILE=/webgateway-shared/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway-shared/CSP.ini
    volumes:
    - ./webgateway:/webgateway-shared
